Fix the tests linking error with -DBUILD_SHARED_LIBS=ON
When build with BUILD_SHARED_LIBS=ON, the tests links with gmock
error:

  /usr/bin/ld: lib/libgmock.so: undefined reference to `testing::internal::ParseInt32(testing::Message const&, char const*, int*)'

which is report by issue: https://github.com/google/leveldb/issues/770

This patch set BUILD_SHARED_LIBS=OFF before enter googletest subdirecory,
and restore the previous value later. By doing this, gtest and gmock
will be build as static library.

I really think this is a bug in googletest CMakeLists, but I didn't dig
into it too much.

The solution might not be that elegant, but it works, maybe we can find
a better way later.

Signed-off-by: Zhao Junwang <zhjwpku@gmail.com>